### ISSUE TITLE
Impossible to see rates from RUR to AMD

### ISSUE THREAD

**Issue by IvanovAndrew** [IvanovAndrew/AmdConverterTelegramBot#11]
Request a conversion from RUR to AMD.
```AmdConverterTelegramBot.Controllers.AmdConverterController[0]
      non cash 15000₽->AMD is received
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMMQM06D5F9J", Request id "0HMMQM06D5F9J:00000009": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Sequence contains no elements
         at System.Linq.ThrowHelper.ThrowNoElementsException()
         at AmdConverterTelegramBot.Controllers.AmdConverterController.FormatTable(IOrderedEnumerable`1 exchanges, Currency currency, Int32 rowNumber, CultureInfo cultureInfo) in C:\Users\warrior_spb\RiderProjects\AmdConverterTelegramBot\AmdConverterTelegramBot\Controllers\AmdConverterController.cs:line 177
         at AmdConverterTelegramBot.Controllers.AmdConverterController.Post(Update update) in C:\Users\warrior_spb\RiderProjects\AmdConverterTelegramBot\AmdConverterTelegramBot\Controllers\AmdConverterController.cs:line 173
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`````

**Comment by IvanovAndrew** [comment]
The reason is that request parser returns a wrong result: 15 000 amd -> 15 000 amd
